name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build (stdio_game_runner)
        run: cargo build --verbose --no-default-features --features "stdio_game_runner"
      - name: Run tests (stdio_game_runner)
        run: cargo test --verbose --no-default-features --features "stdio_game_runner"
      - name: Build (ratatui_game_runner)
        run: cargo build --verbose --no-default-features --features "ratatui_game_runner"
      - name: Run tests (ratatui_game_runner)
        run: cargo test --verbose --no-default-features --features "ratatui_game_runner"
